namespace CodeDesignPlus.Net.Microservice.Payments.Application.Payment.DataTransferObjects;

/// <summary>
/// DTO de respuesta estandarizado para la operación de tokenización de tarjeta.
/// </summary>
public class TokenizeCardResponseDto
{
    /// <summary>
    /// The secure Token ID generated by the gateway. This is what you save in your database.
    /// </summary>
    public string? CreditCardTokenId { get; set; }

    /// <summary>
    /// The status of the tokenization (e.g., "APPROVED").
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Identifier of the payer in the payment gateway.
    /// </summary>
    public string? PayerId { get; set; }

    /// <summary>
    /// The identification number (DNI) associated with the cardholder.
    /// </summary>
    public string? IdentificationNumber { get; set; }

    /// <summary>
    /// The franchise or payment method (e.g., "VISA").
    /// </summary>
    public string? PaymentMethod { get; set; }

    /// <summary>
    /// The masked card number safe for display (e.g., "403799******1984").
    /// </summary>
    public string? MaskedNumber { get; set; }

    /// <summary>
    /// Description of the error if the tokenization failed.
    /// </summary>
    public string? ErrorDescription { get; set; }
}
