using System;

namespace CodeDesignPlus.Net.Microservice.Payments.Infrastructure.Services.Payu.Models;


/// <summary>
/// Represents the response from the payment gateway after attempting to tokenize a credit card.
/// </summary>
public class CreditCardTokenResponse
{
    /// <summary>
    /// The response code from the payment gateway.
    /// </summary>
    public string Code { get; set; } = null!;
    /// <summary>
    /// The error message from the payment gateway, if any.
    /// </summary>
    public string Error { get; set; } = null!;
    /// <summary>
    /// The tokenized credit card information.
    /// </summary>
    public CreditCardToken CreditCardToken { get; set; } = null!;
}

/// <summary>
/// Represents the response payload from the payment gateway after a successful or failed card tokenization.
/// </summary>
public class CreditCardToken
{
    /// <summary>
    /// The secure Token ID generated by the gateway. This is what you save in your database.
    /// </summary>
    public string? CreditCardTokenId { get; set; }

    /// <summary>
    /// The status of the tokenization (e.g., "APPROVED").
    /// </summary>
    public string? Name { get; set; }

    /// <summary>
    /// Identifier of the payer in the payment gateway.
    /// </summary>
    public string? PayerId { get; set; }

    /// <summary>
    /// The identification number (DNI) associated with the cardholder.
    /// </summary>
    public string? IdentificationNumber { get; set; }

    /// <summary>
    /// The franchise or payment method (e.g., "VISA").
    /// </summary>
    public string? PaymentMethod { get; set; }

    /// <summary>
    /// The masked card number safe for display (e.g., "403799******1984").
    /// </summary>
    public string? MaskedNumber { get; set; }

    /// <summary>
    /// Description of the error if the tokenization failed.
    /// </summary>
    public string? ErrorDescription { get; set; }
}