namespace CodeDesignPlus.Net.Microservice.Payments.Infrastructure.Services.Payu.Models;



/// <summary>
/// Represents a request to the PayU payment gateway.
/// </summary>
public class CreditCardTokenRequest
{
  /// <summary>
  /// Language used in the request, this language is used to display error messages generated.
  /// </summary>
  public string Language { get; set; } = null!;
  /// <summary>
  /// Assigns CREATE_TOKEN.
  /// </summary>
  public string Command { get; } = "CREATE_TOKEN";
  /// <summary>
  /// This object contains the authentication data.
  /// </summary>
  public Merchant Merchant { get; set; } = null!;
  /// <summary>
  /// This object contains the transaction data.
  /// </summary>
  public CreditCardTokenPayload CreditCardToken { get; set; } = null!;
}

/// <summary>
/// Represents the request to the payment gateway (e.g., PayU) for card tokenization.
/// </summary>
public class CreditCardTokenPayload
{
    /// <summary>
    /// Identifier of the payer in the payment gateway.
    /// </summary>
    public string PayerId { get; set; } = null!;
    /// <summary>
    /// The name of the token or the status (e.g., "APPROVED").
    /// </summary>
    public string Name { get; set; } = null!;
    /// <summary>
    /// The identification number (DNI) associated with the cardholder.
    /// </summary>
    public string IdentificationNumber { get; set; } = null!;
    /// <summary>
    /// The franchise or payment method (e.g., "VISA", "MASTERCARD").
    /// </summary>
    public string PaymentMethod { get; set; } = null!;
    /// <summary>
    /// The actual secure Token ID generated by the gateway. 
    /// (Note: Even though the JSON says "number", in tokenization responses this usually contains the alphanumeric token, not the PAN).
    /// </summary>
    public string Number { get; set; } = null!;
    /// <summary>
    /// The expiration date of the tokenized card in YYYY/MM format.
    /// </summary>
    public string ExpirationDate { get; set; } = null!;
}