using System;

namespace CodeDesignPlus.Net.Microservice.Payments.Infrastructure.Services.Payu.Models;

/// <summary>
/// Represents the response from PayU after processing a transaction.
/// </summary>
public class PayuResponse
{
    /// <summary>
    /// Gets or sets the response code of the transaction. 
    /// Possible values are "ERROR" and "SUCCESS".
    /// </summary>
    public string Code { get; set; } = null!;
    /// <summary>
    /// Gets or sets the error message associated with the transaction response.
    /// This is only populated when the response code is "ERROR".
    /// </summary>
    public string? Error { get; set; }
    /// <summary>
    /// Gets or sets the transaction response details.
    /// This includes information such as order ID, transaction ID, state, response code,
    /// </summary>
    public TransactionResponse TransactionResponse { get; set; } = null!;
}

/// <summary>
/// Represents the details of a transaction response from PayU.
/// </summary>
public class TransactionResponse
{
    /// <summary>
    /// Gets or sets the unique identifier for the order in PayU.
    /// This is either generated by PayU or an existing identifier.
    /// </summary>
    public long OrderId { get; set; }
    /// <summary>
    /// Gets or sets the unique identifier for the transaction in PayU.
    /// This is a 36-character alphanumeric string.
    /// </summary>
    public string TransactionId { get; set; } = null!;
    /// <summary>
    /// Gets or sets the state of the transaction.
    /// This is a string that can have various values indicating the status of the transaction.
    /// </summary>
    public string State { get; set; } = null!;
    /// <summary>
    /// Gets or sets the response code associated with the transaction state.
    /// This is a string that can have various values indicating the outcome of the transaction.
    /// </summary>
    public string ResponseCode { get; set; } = null!;
    /// <summary>
    /// Gets or sets the payment network response code.
    /// This is a string that can have various values returned by the banking network.
    /// </summary>
    public string? PaymentNetworkResponseCode { get; set; }
    /// <summary>
    /// Gets or sets the error message returned by the payment network.
    /// This is a string that can have various values indicating any issues encountered by the banking network.
    /// </summary>
    public string? PaymentNetworkResponseErrorMessage { get; set; }
    /// <summary>
    /// Gets or sets the trazability code returned by the banking network.
    /// This is a string that can have various values indicating the traceability of the transaction.
    /// </summary>
    public string? TrazabilityCode { get; set; }
    /// <summary>
    /// Gets or sets the authorization code returned by the banking network.
    /// This is a string that can have various values indicating the authorization status of the transaction.
    /// </summary>
    public string? AuthorizationCode { get; set; }
    /// <summary>
    /// Gets or sets the response message associated with the transaction response code.
    /// This is a string that can have various values providing additional context or information about the transaction.
    /// </summary>
    public string ResponseMessage { get; set; } = null!;
    /// <summary>
    /// Gets or sets the date and time when the transaction response was created in the PayU system.
    /// This is a DateTime value representing the operation date of the transaction.
    /// </summary>
    public DateTime OperationDate { get; set; }
    /// <summary>
    /// Gets or sets additional parameters or data associated with the transaction response.
    /// This is a dictionary where the key is a string and the value is also a string.
    /// </summary>
    public Dictionary<string, string> ExtraParameters { get; set; } = [];
    /// <summary>
    /// Gets or sets additional information related to the transaction response.
    /// This is a dictionary where the key is a string and the value can be any object.
    /// </summary>
    public Dictionary<string, object> AdditionalInfo { get; set; } = [];
}
